import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  Accordion,
  Box,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
  Container,
} from '@chakra-ui/react'
import Nav from '../components/nav';
import Footer from '../components/footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav/>
      <main className={styles.main}>
        <Container maxW="container.xl">
          <h1>content here</h1>
        </Container>
      </main>
      <Footer/>
    </div>
  )
}
